import Foundation

public enum SensitiveReason: String, Sendable {
    case concealedPasteboard, ignoredApp
    case privateKey, awsKey, apiToken, jwt, credentialAssignment, credentialURL
    case creditCard, otp, seedPhrase, highEntropy
}

public struct SensitiveVerdict: Equatable, Sendable {
    public let reason: SensitiveReason
}

/// Decides whether a clipboard entry must NOT be persisted. Runs before any storage.
/// Cheapest / most reliable checks first; first hit wins.
public struct SensitiveContentDetector: Sendable {
    /// Pasteboard type identifiers that password managers & apps use to flag secrets.
    public static let concealedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType", "com.typeit4me.clipping",
        "Pasteboard generator type",
    ]
    public static let defaultIgnoredBundles: Set<String> = [
        "com.1password.1password", "com.agilebits.onepassword7", "com.agilebits.onepassword-osx",
        "com.1password.1password7", "com.bitwarden.desktop", "org.keepassxc.keepassxc",
        "com.dashlane.dashlanephonefinal", "com.lastpass.lastpassmacdesktop",
        "com.apple.keychainaccess", "com.apple.Passwords", "org.keepassx.keepassxc",
    ]

    public var ignoredBundles: Set<String>
    /// Treat bare 4-8 digit copies as OTPs and drop them.
    public var dropBareNumericCodes: Bool

    public init(ignoredBundles: Set<String> = SensitiveContentDetector.defaultIgnoredBundles,
                dropBareNumericCodes: Bool = true) {
        self.ignoredBundles = Set(ignoredBundles.map { $0.lowercased() })
        self.dropBareNumericCodes = dropBareNumericCodes
    }

    /// Layer 1+2: metadata checks that need no content inspection.
    public func checkMetadata(pasteboardTypes: [String], sourceBundle: String?) -> SensitiveVerdict? {
        if pasteboardTypes.contains(where: Self.concealedTypes.contains) { return .init(reason: .concealedPasteboard) }
        if let b = sourceBundle?.lowercased(), ignoredBundles.contains(b) { return .init(reason: .ignoredApp) }
        return nil
    }

    /// Layers 3-8: content inspection.
    public func check(text: String) -> SensitiveVerdict? {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return nil }
        // Huge blobs are not secrets; avoid regex cost. Scan only the first 20k chars.
        let s = trimmed.count > 20_000 ? String(trimmed.prefix(20_000)) : trimmed

        if Self.has(Self.privateKey, in: s) { return .init(reason: .privateKey) }
        if Self.has(Self.awsAccessKey, in: s) { return .init(reason: .awsKey) }
        if Self.has(Self.tokenPatterns, in: s) { return .init(reason: .apiToken) }
        if Self.containsJWT(s) { return .init(reason: .jwt) }
        if Self.has(Self.credentialURL, in: s) { return .init(reason: .credentialURL) }
        if Self.has(Self.bearerOrCookie, in: s) || Self.hasCredentialAssignment(s) { return .init(reason: .credentialAssignment) }
        if Self.containsCard(s) { return .init(reason: .creditCard) }
        if Self.isOTP(s, dropBare: dropBareNumericCodes) { return .init(reason: .otp) }
        if Self.looksLikeSeedPhrase(s) { return .init(reason: .seedPhrase) }
        if Self.isHighEntropySecret(s) { return .init(reason: .highEntropy) }
        return nil
    }

    // MARK: Patterns

    private static func re(_ p: String, _ o: NSRegularExpression.Options = []) -> NSRegularExpression {
        try! NSRegularExpression(pattern: p, options: o)
    }
    private static func has(_ r: NSRegularExpression, in s: String) -> Bool {
        r.firstMatch(in: s, range: NSRange(s.startIndex..., in: s)) != nil
    }
    private static func has(_ rs: [NSRegularExpression], in s: String) -> Bool { rs.contains { has($0, in: s) } }

    static let privateKey = re("-----BEGIN [A-Z0-9 ]*PRIVATE KEY( BLOCK)?-----")
    static let awsAccessKey = re("\\b(AKIA|ASIA|AGPA|AIDA|AROA)[0-9A-Z]{16}\\b")
    static let tokenPatterns: [NSRegularExpression] = [
        re("\\bgh[pousr]_[A-Za-z0-9]{36,}\\b"), re("\\bgithub_pat_[A-Za-z0-9_]{22,}\\b"),
        re("\\bglpat-[A-Za-z0-9_\\-]{20,}\\b"), re("\\bxox[abprs]-[A-Za-z0-9-]{10,}\\b"),
        re("\\b[sr]k_live_[A-Za-z0-9]{16,}\\b"), re("\\bAIza[0-9A-Za-z_\\-]{35}\\b"),
        re("\\bsk-ant-[A-Za-z0-9_\\-]{20,}\\b"), re("\\bsk-(proj-)?[A-Za-z0-9_\\-]{32,}\\b"),
        re("\\bnpm_[A-Za-z0-9]{36}\\b"), re("\\bSG\\.[A-Za-z0-9_\\-]{16,}\\.[A-Za-z0-9_\\-]{16,}\\b"),
        re("\\bhf_[A-Za-z0-9]{30,}\\b"), re("\\bshp(at|ss|ca|pa)_[a-f0-9]{32}\\b"),
    ]
    static let credentialURL = re("[a-z][a-z0-9+.\\-]*://[^\\s/:@]+:[^\\s/@]+@[^\\s]+", .caseInsensitive)
    static let bearerOrCookie = re("(^|\\n)\\s*(authorization\\s*:\\s*(bearer|basic|token)\\s+\\S+|(set-)?cookie\\s*:\\s*\\S*(session|token|auth|sid)\\S*=)", .caseInsensitive)
    static let assignment = re("\\b(pass(word|wd)?|pwd|secret|(api|access|auth|private)[_\\- ]?(key|token)|token|client[_\\-]?secret|aws_secret_access_key)\\b\\s*[:=]\\s*[\"']?([^\\s\"']{6,})", .caseInsensitive)
    static let jwtRegex = re("\\beyJ[A-Za-z0-9_\\-]{5,}\\.eyJ[A-Za-z0-9_\\-]{5,}\\.[A-Za-z0-9_\\-]{5,}\\b")

    private static func containsJWT(_ s: String) -> Bool {
        guard let m = jwtRegex.firstMatch(in: s, range: NSRange(s.startIndex..., in: s)),
              let r = Range(m.range, in: s) else { return false }
        let header = s[r].split(separator: ".")[0]
        var b64 = header.replacingOccurrences(of: "-", with: "+").replacingOccurrences(of: "_", with: "/")
        while b64.count % 4 != 0 { b64 += "=" }
        guard let data = Data(base64Encoded: b64), let obj = try? JSONSerialization.jsonObject(with: data) else { return false }
        return obj is [String: Any]
    }

    private static func hasCredentialAssignment(_ s: String) -> Bool {
        let ns = s as NSString
        for m in assignment.matches(in: s, range: NSRange(location: 0, length: ns.length)) {
            let value = ns.substring(with: m.range(at: m.numberOfRanges - 1))
            // Ignore obvious placeholders / references.
            let lower = value.lowercased()
            if lower.contains("(") && lower.hasSuffix(")") || lower.hasPrefix("$") || lower.hasPrefix("{{") || lower.hasPrefix("<") || lower.hasPrefix("process.env")
                || ["null", "none", "undefined", "string", "true", "false", "password", "your_password"].contains(lower) { continue }
            return true
        }
        return false
    }

    // MARK: Credit cards (Luhn + IIN)

    static let cardCandidate = re("(?<![\\d])(?:\\d[ \\-]?){12,18}\\d(?![\\d])")
    private static func containsCard(_ s: String) -> Bool {
        let ns = s as NSString
        for m in cardCandidate.matches(in: s, range: NSRange(location: 0, length: ns.length)) {
            let digits = ns.substring(with: m.range).filter(\.isNumber)
            if (13...19).contains(digits.count), luhn(digits), plausibleIIN(digits) { return true }
        }
        return false
    }
    static func luhn(_ digits: String) -> Bool {
        var sum = 0, alt = false
        for ch in digits.reversed() {
            guard var d = ch.wholeNumberValue else { return false }
            if alt { d *= 2; if d > 9 { d -= 9 } }
            sum += d; alt.toggle()
        }
        return sum % 10 == 0
    }
    private static func plausibleIIN(_ d: String) -> Bool {
        let p2 = Int(d.prefix(2)) ?? 0, p4 = Int(d.prefix(4)) ?? 0, p1 = Int(d.prefix(1)) ?? 0
        if p1 == 4 { return true }                                  // Visa
        if (51...55).contains(p2) || (2221...2720).contains(p4) { return true } // Mastercard
        if p2 == 34 || p2 == 37 { return true }                     // Amex
        if p2 == 62 || p2 == 36 || p2 == 38 || p4 == 6011 || p2 == 65 { return true } // Discover/UnionPay/Diners
        if (3528...3589).contains(p4) { return true }               // JCB
        return false
    }

    // MARK: OTP

    private static func isOTP(_ s: String, dropBare: Bool) -> Bool {
        guard dropBare, s.count <= 9 else { return false }
        let stripped = s.replacingOccurrences(of: "-", with: "").replacingOccurrences(of: " ", with: "")
        return (4...8).contains(stripped.count) && stripped.allSatisfy(\.isASCII) && stripped.allSatisfy(\.isNumber)
    }

    // MARK: Seed phrases (heuristic; a bundled BIP-39 list is a planned upgrade)

    private static let stopwords: Set<String> = ["the", "and", "is", "are", "was", "for", "that", "this", "with", "you", "have", "not", "but", "your", "will", "can", "from"]
    private static func looksLikeSeedPhrase(_ s: String) -> Bool {
        let words = s.split(whereSeparator: { $0 == " " || $0 == "\n" }).map(String.init)
        guard [12, 15, 18, 21, 24].contains(words.count) else { return false }
        guard words.allSatisfy({ (3...8).contains($0.count) && $0.allSatisfy { $0.isASCII && $0.isLowercase && $0.isLetter } }) else { return false }
        return words.filter { stopwords.contains($0) }.count < 2
    }

    // MARK: Entropy

    static func shannonEntropy(_ s: String) -> Double {
        var freq: [Character: Int] = [:]
        for c in s { freq[c, default: 0] += 1 }
        let n = Double(s.count)
        return -freq.values.reduce(0.0) { $0 + (Double($1) / n) * log2(Double($1) / n) }
    }
    private static let uuid = re("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")
    private static let gitSHA = re("^[0-9a-f]{40}$|^[0-9a-f]{64}$|^[0-9a-f]{7,12}$")

    private static func isHighEntropySecret(_ s: String) -> Bool {
        guard (20...256).contains(s.count), !s.contains(where: \.isWhitespace) else { return false }
        if s.contains("://") || s.hasPrefix("/") || s.hasPrefix("~") || s.hasPrefix("./") || s.contains("@") && s.contains(".") && !s.contains("=") { return false }
        if has(uuid, in: s) || has(gitSHA, in: s) { return false }
        let hasLower = s.contains(where: \.isLowercase), hasUpper = s.contains(where: \.isUppercase)
        let hasDigit = s.contains(where: \.isNumber), hasSym = s.contains { !$0.isLetter && !$0.isNumber }
        let classes = [hasLower, hasUpper, hasDigit, hasSym].filter { $0 }.count
        let e = shannonEntropy(s)
        let isHex = s.allSatisfy(\.isHexDigit)
        if isHex { return e >= 3.5 && s.count >= 32 }
        return classes >= 3 && e >= 4.0
    }
}
